<?php

namespace Acme\CentralaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NamesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NamesRepository extends EntityRepository
{
     public function findAllByName($ime)
      {
       
        return $this->getEntityManager()
          
        ->createQuery('SELECT u FROM AcmeCentralaBundle:Names u WHERE u.name LIKE :name  ')
        ->setParameter('name', $ime.'%') 
        ->setMaxResults(1000)      
        ->getResult();

        
      } 
}
