<?php

namespace Acme\CentralaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VezeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VezeRepository extends EntityRepository
{
}
