<?php

namespace Proxies\__CG__\Acme\CentralaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Veze extends \Acme\CentralaBundle\Entity\Veze implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'idveza', 'vlasnik', 'vidljivost', 'vcard', 'names', 'numbers');
        }

        return array('__isInitialized__', 'idveza', 'vlasnik', 'vidljivost', 'vcard', 'names', 'numbers');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Veze $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdveza()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdveza();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdveza', array());

        return parent::getIdveza();
    }

    /**
     * {@inheritDoc}
     */
    public function setVlasnik($vlasnik)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVlasnik', array($vlasnik));

        return parent::setVlasnik($vlasnik);
    }

    /**
     * {@inheritDoc}
     */
    public function getVlasnik()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVlasnik', array());

        return parent::getVlasnik();
    }

    /**
     * {@inheritDoc}
     */
    public function setVidljivost($vidljivost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVidljivost', array($vidljivost));

        return parent::setVidljivost($vidljivost);
    }

    /**
     * {@inheritDoc}
     */
    public function getVidljivost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVidljivost', array());

        return parent::getVidljivost();
    }

    /**
     * {@inheritDoc}
     */
    public function addVcard(\Acme\CentralaBundle\Entity\Vcard $vcard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVcard', array($vcard));

        return parent::addVcard($vcard);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVcard(\Acme\CentralaBundle\Entity\Vcard $vcard)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVcard', array($vcard));

        return parent::removeVcard($vcard);
    }

    /**
     * {@inheritDoc}
     */
    public function getVcard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVcard', array());

        return parent::getVcard();
    }

    /**
     * {@inheritDoc}
     */
    public function addName(\Acme\CentralaBundle\Entity\Vcard $names)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addName', array($names));

        return parent::addName($names);
    }

    /**
     * {@inheritDoc}
     */
    public function removeName(\Acme\CentralaBundle\Entity\Vcard $names)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeName', array($names));

        return parent::removeName($names);
    }

    /**
     * {@inheritDoc}
     */
    public function getNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNames', array());

        return parent::getNames();
    }

    /**
     * {@inheritDoc}
     */
    public function addNumber(\Acme\CentralaBundle\Entity\Vcard $numbers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNumber', array($numbers));

        return parent::addNumber($numbers);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNumber(\Acme\CentralaBundle\Entity\Vcard $numbers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNumber', array($numbers));

        return parent::removeNumber($numbers);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumbers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumbers', array());

        return parent::getNumbers();
    }

}
